# -*- coding: utf-8 -*-
"""Camylla Oliveira - Modulo 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uA0WV03I0fJ_3qrYCu9lfEKPkpHbqofe

## Módulo 8: Projeto Final

Integrando conhecimentos adquiridos no curso.

##### Este código inclui a leitura de um arquivo CSV, visualização de dados e algumas operações básicas de análise, como média e correlação.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Carregar os dados
arquivo_csv = 'Camylla Oliveira - dados_projeto_final.csv'  # Substitua pelo caminho do seu arquivo CSV
dados = pd.read_csv(arquivo_csv)

# Exibir as primeiras linhas dos dados para revisão
dados.head()

# Análise básica
print("\nEstatísticas descritivas dos dados:")
print(dados.describe())  # Exibe estatísticas como média, desvio padrão, etc.

# Exemplo de análise - Média da Renda Mensal
media_renda = dados['Renda Mensal'].mean()
print(f"\nMédia da Renda Mensal: {media_renda}")

# Média de Idade
media_idade = dados['Idade'].mean()
print(f"\nMédia de Idade: {media_idade:.1f} anos")

# Média de Compras Online
media_compras = dados['Número de Compras Online'].mean()
print(f"Média de Compras Online: {media_compras:.1f} compras")

# Média de Satisfação
media_satisfacao = dados['Satisfação do Cliente (1-10)'].mean()
print(f"Média de Satisfação: {media_satisfacao:.1f}/10")

# Exemplo de visualização - Gráfico de dispersão entre Renda Mensal e Número de Compras Online
plt.scatter(dados['Renda Mensal'], dados['Número de Compras Online'])
plt.title('Renda Mensal vs Número de Compras Online')
plt.xlabel('Renda Mensal')
plt.ylabel('Número de Compras Online')
plt.show()

# Gráfico de Barras - Média de Satisfação por Gênero
media_satisfacao = dados.groupby('Gênero')['Satisfação do Cliente (1-10)'].mean()

plt.bar(media_satisfacao.index, media_satisfacao.values)
plt.title('Média de Satisfação por Gênero')
plt.xlabel('Gênero')
plt.ylabel('Média de Satisfação (1-10)')
plt.show()

# Exemplo de análise - Correlação entre variáveis
correlacao = dados[['Renda Mensal', 'Número de Compras Online']].corr()
print("\nCorrelação entre Renda Mensal e Número de Compras Online:")
print(correlacao)

# 2. Correlação
correlacao = dados['Renda Mensal'].corr(dados['Número de Compras Online'])
print(f"\nCorrelação Renda x Compras: {correlacao:.2f}")

# Filtragem de dados - Exemplo de seleção de dados com base em uma condição (Renda Mensal > 5000)
dados_filtrados = dados[dados['Renda Mensal'] > 5000]
print("\nDados filtrados (Renda Mensal > 5000):")
print(dados_filtrados)

# Análise por Gênero
print("\nMédias por Gênero:")
for genero in dados['Gênero'].unique():
    subset = dados[dados['Gênero'] == genero]
    print(f"\n{genero}:")
    print(f"- Média Renda: R$ {subset['Renda Mensal'].mean():.2f}")
    print(f"- Média Compras: {subset['Número de Compras Online'].mean():.1f}")
    print(f"- Média Satisfação: {subset['Satisfação do Cliente (1-10)'].mean():.1f}/10")

# Filtro de clientes com mais de 30 anos e menos de 5 compras online
clientes_filtrados = dados[(dados['Idade'] > 30) & (dados['Número de Compras Online'] < 5)]

print("\nClientes com mais de 30 anos e menos de 5 compras online:")
print(clientes_filtrados[['ID', 'Nome', 'Idade', 'Número de Compras Online']].to_string(index=False))
print("\nTotal encontrado:", len(clientes_filtrados))

# Cálculo IQR
Q1 = dados['Renda Mensal'].quantile(0.25)
Q3 = dados['Renda Mensal'].quantile(0.75)
IQR = Q3 - Q1
limite_superior = Q3 + 1.5 * IQR

# Análise
print("\n6. Análise de Outliers na Renda Mensal")
print(f"Limite superior (IQR): R$ {limite_superior:.2f}")
print("\nDistribuição de Renda:")
print(dados['Renda Mensal'].describe().to_string())
print("\nOutliers identificados: 0 (Nenhum valor acima do limite superior)")

plt.figure(figsize=(6,4))
dados.boxplot(column='Renda Mensal', vert=False)
plt.title('Distribuição da Renda Mensal')
plt.show()

# Salvar o relatório com os resultados da análise em um arquivo de texto
with open('relatorio_analise.txt', 'w') as file:
    file.write(f"Média da Renda Mensal: {media_renda}\n")
    file.write("Correlação entre Renda Mensal e Número de Compras Online:\n")
    file.write(f"{correlacao}\n")
    file.write(f"Dados filtrados (Renda Mensal > 5000):\n{dados_filtrados}\n")

print("\nRelatório salvo como 'relatorio_analise.txt'.")